In [3]:
from bs4 import BeautifulSoup 
import requests

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/148.0.0.0 Safari/537.36"
}

url = "https://en.wikipedia.org/wiki/List_of_largest_companies_in_the_United_States_by_revenue"
response = requests.get(url, headers=headers)
soup = BeautifulSoup(response.text, 'html')

In [13]:
table1 = soup.find_all('table')[1]
table2 = soup.find_all('table')[0]
#print(table2)

In [25]:
world_titles = table1.find_all('th')
world_titles2= table2.find_all('th')
#print(world_titles2)

In [15]:
table_titles = [title.text.strip() for title in world_titles]
print(table_titles)

table_titles2 = [title.text.strip() for title in world_titles2]
print(table_titles2)

['Rank', 'Name', 'Industry', 'Revenue (USD billions)', 'Employees', 'Headquarters']
['Rank', 'Name', 'Industry', 'Revenue (USD millions)', 'Revenue growth', 'Employees', 'Headquarters']

In [20]:
import pandas as pd

df = pd.DataFrame(columns = table_titles)
df2 = pd.DataFrame(columns = table_titles2)

df

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD billions), Employees, Headquarters]
Index: []

In [21]:
df2

Empty DataFrame
Columns: [Rank, Name, Industry, Revenue (USD millions), Revenue growth, Employees, Headquarters]
Index: []

In [27]:
#tr - all rows, td - data in each rows

In [10]:
all_rows = table1.find_all('tr')
for row in all_rows[1:]:
    row_values = row.find_all('td')
    value = [each_value.text.strip() for each_value in row_values]
    
    length = len(df)
    df.loc[length] = value
    df

In [9]:
df.to_csv(r'C:\Users\Dell\Downloads\pythontutorials\companies.csv', index = False)

In [23]:
all_rows2 = table2.find_all('tr')
for row in all_rows2[1:]:
    row_values2 = row.find_all('td')
    value2 = [each_value.text.strip() for each_value in row_values2]
    
    length = len(df2)
    df2.loc[length] = value2
    df2

In [24]:
df2.to_csv(r'C:\Users\Dell\Downloads\pythontutorials\companies2.csv', index = False)